################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
HALCoGen-TMS570LS12x/source/dabort.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/dabort.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/dabort.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/emac.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/emac.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/emac.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/esm.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/esm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/esm.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/mdio.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/mdio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/mdio.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/notification.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/notification.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/notification.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/phy_dp83640.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/phy_dp83640.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/phy_dp83640.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/pinmux.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/pinmux.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/pinmux.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sci.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sci.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sci.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_core.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_core.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_core.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_dma.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_dma.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_dma.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_intvecs.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_intvecs.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_intvecs.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_main.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_main.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_main.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_mpu.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_mpu.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_mpu.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_pcr.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_pcr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_pcr.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_phantom.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_phantom.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_phantom.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_pmm.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_pmm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_pmm.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_pmu.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_pmu.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_pmu.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_selftest.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_selftest.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_selftest.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_startup.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_startup.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_startup.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/sys_vim.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/sys_vim.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/sys_vim.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-TMS570LS12x/source/system.obj: /home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/source/system.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -g --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="/opt/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk" --include_path="/home/slee/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/TMS570LS12x/HALCoGen-TMS570LS12x/include" --include_path="/home/slee/repos/code/lwipHerculesExamples/example/hdk/inc" --diag_warning=225 --display_error_number --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-TMS570LS12x/source/system.d" --obj_directory="HALCoGen-TMS570LS12x/source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '


