################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
HALCoGen-RM57x/source/HL_emac.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_emac.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_emac.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_epc.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_epc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_epc.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_errata.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_errata.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_errata.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_esm.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_esm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_esm.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_mdio.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_mdio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_mdio.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_nmpu.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_nmpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_nmpu.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_notification.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_notification.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_notification.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_phy_dp83640.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_phy_dp83640.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_phy_dp83640.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_pinmux.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_pinmux.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_pinmux.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sci.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sci.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sci.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_core.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_core.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_core.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_dma.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_dma.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_dma.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_intvecs.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_intvecs.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_intvecs.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_main.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_main.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_main.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_mpu.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_mpu.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_mpu.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_pcr.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_pcr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_pcr.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_phantom.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_phantom.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_phantom.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_pmm.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_pmm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_pmm.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_pmu.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_pmu.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_pmu.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_startup.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_startup.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_startup.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_sys_vim.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_sys_vim.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_sys_vim.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

HALCoGen-RM57x/source/HL_system.obj: C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/source/HL_system.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/bin/armcl" -mv7R4 --code_state=32 --float_support=VFPv3D16 --abi=eabi -me --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/RM57x/HALCoGen-RM57x/include" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/check" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/apps/httpserver_raw" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include/ipv4" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/ports/hdk/netif" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/lwip-1.4.1/src/include" --include_path="C:/Users/sleewin/repos/code/lwipHerculesExamples/example/hdk/inc" -g --define=_RM57Lx_ --display_error_number --diag_warning=225 --diag_wrap=off --enum_type=packed --preproc_with_compile --preproc_dependency="HALCoGen-RM57x/source/HL_system.d" --obj_directory="HALCoGen-RM57x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


